#端口
server:
  port: 8080

#连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education_manage2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: "root"
    password: "akmm1412"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  #xml位置
  mapper-locations: classpath:mapper/*.xml
  #实体类位置
  type-aliases-package: com.example.educationManage.model